jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
     - name: Clean up old artifacts
        run: |
          rm -rf ./path/to/artifact1
          rm -rf ./path/to/artifact2
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact-1
        path: path/to/artifact1

    - name: Upload more artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact-2
        path: path/to/artifact2