name: Install faraday-retry gem

on: [push, pull_request]

jobs: 
  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install faraday-retry gem
      run: gem install faraday-retry